repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
            args: [--allow-multiple-documents]
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: check-merge-conflict
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.4.1
      hooks:
          - id: prettier
            types_or: [javascript, markdown]
